version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - web
  redis:
    image: redis:alpine
    networks:
      - web